### ISSUE TITLE
pycors always tries to install `3.9.0` on Linux

### ISSUE THREAD

**Issue by tkamenoko** [nbigaouette/pycors#100]
platform: KDE neon User Edition 5.17(based on ubuntu)
pycors: 0.2.1

pycors always tries (and fails) to install `3.9.0` against any `python` versions.

`$ pycors install 3.8.0`
>[2019-12-10T03:47:12Z INFO  pycors::cache] Using cache (0 days old)
[2019-12-10T03:47:12Z ERROR pycors::toolchain] Failed to parse version string "2.7.15+": ParseError("Error parsing prerelease")
[2019-12-10T03:47:12Z ERROR pycors::toolchain] Failed to parse version string "2.7.15+": ParseError("Error parsing prerelease")
[2019-12-10T03:47:12Z INFO  pycors::commands::install] Installing Python 3.9.0 (from https://www.python.org/ftp/python/3.9.0)
[2019-12-10T03:47:12Z INFO  pycors::download] Downloading https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tgz...
Error: Failed to query python.org: Response { status: 404, version: HTTP/1.1, headers: {"server": "nginx", "content-type": "text/html", "x-clacks-overhead": "GNU Terry Pratchett", "via": "1.1 varnish", "via": "1.1 varnish", "content-length": "162", "accept-ranges": "bytes", "date": "Tue, 10 Dec 2019 03:47:13 GMT", "age": "371", "connection": "keep-alive", "x-served-by": "cache-jfk8121-JFK, cache-hnd18744-HND", "x-cache": "MISS, HIT", "x-cache-hits": "0, 1", "x-timer": "S1575949634.863530,VS0,VE0", "strict-transport-security": "max-age=63072000; includeSubDomains"}, body: Body(Streaming) }

**Comment by nbigaouette** [comment]
This is caused by semantic versioning interpretation.

By default, without any prefix character to the version provided (here `3.8.0`), the `semver` crate interpret the requested version as `^3.8.0`, which means `>=3.8.0, < 4.0.0`. The latest Python version matching this is 3.9.0 and hence this is the one being attempted to download.

Unfortunately, 3.9.0 is not yet released and is only available as pre-release (see directory listing here: https://www.python.org/ftp/python/3.9.0/). Hence why it is failing.

What you want is to request _an exact_ version to install. To do this, simply prepend the version with `=`:

```sh
pycors install =3.8.0
```

**Comment by nbigaouette** [comment]
I've opened #101 regarding the confusing behavior.
